# Tensorflow构建cnn模型实现情感分析
本文使用tensorflow框架构建cnn模型，实现口碑数据的情感分析.模型的主要信息如下：
- 输入数据:使用` gensim.models.doc2vec.Doc2Vec(dm=0,dbow_words=1,size=80,min_count=2,iter=55,workers=cores,window=8)`构建PV_DBOW_model模型生成的文本向量
- 模型效果：效果不佳，分类正确率仅0.6左右
- 效果不佳原因：输入数据是80维的doc2vec PV_DBOW_model生成的文本向量，PV_DBOW_mode self-similarity评估效果0.756左右（similar doc per model>0.9句向量表示效果好），故该文本向量表示文本的效果不太好。基于不太理想的数据构建的cnn模型，分类的效果也不会太好

## 读入训练/测试数据

In [1]:
import pandas as pd
pd_train = pd.read_csv('./data/pd_train.csv')
pd_test = pd.read_csv('./data/pd_test.csv')

In [2]:
feature = [str(i) for i in range(80)]

In [3]:
pd_train[feature].as_matrix().shape

(75000, 80)

In [4]:
pd_train['score'].as_matrix().dtype

dtype('int64')

In [5]:
#数据格式为np.array
train_data = pd_train[feature].as_matrix()
#修改数值类型从float64改成float32
train_data = train_data.astype('float32')
train_labels =pd_train['score'].as_matrix()
eval_data = pd_test[feature].as_matrix()
#修改数值类型从float64改成float32
eval_data = eval_data.astype('float32')
eval_labels = pd_test['score'].as_matrix()

In [6]:
train_data.dtype

dtype('float32')

## 构建cnn模型

In [7]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# Imports
import numpy as np
import tensorflow as tf

tf.logging.set_verbosity(tf.logging.INFO)

In [8]:
def cnn_model_fn(features, labels, mode):
    """Model function for CNN."""
    # Input Layer
    input_layer = tf.reshape(features["x"], [-1, 80, 1, 1])

    # Convolutional Layer #1
    conv1 = tf.layers.conv2d(
        inputs=input_layer,
        filters=4,
        kernel_size=[10, 1],
        padding="same",
        activation=tf.nn.relu)

    # Pooling Layer #1
    pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 1], strides=2)
    '''
    # Convolutional Layer #2 and Pooling Layer #2
    conv2 = tf.layers.conv2d(
        inputs=pool1,
        filters=8,
        kernel_size=[2, 1],
        padding="same",
        activation=tf.nn.relu)
    pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[2, 1], strides=2)
 '''
    # Dense Layer
    pool2_flat = tf.reshape(pool1, [-1, 40* 1 * 4])
    dense = tf.layers.dense(inputs=pool2_flat, units=32, activation=tf.nn.relu)
    dropout = tf.layers.dropout(
      inputs=dense, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)

    # Logits Layer
    logits = tf.layers.dense(inputs=dropout, units=6)

    predictions = {
      # Generate predictions (for PREDICT and EVAL mode)
      "classes": tf.argmax(input=logits, axis=1),
      # Add `softmax_tensor` to the graph. It is used for PREDICT and by the
      # `logging_hook`.
      "probabilities": tf.nn.softmax(logits, name="softmax_tensor")
  }

    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)

    # Calculate Loss (for both TRAIN and EVAL modes)
    loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)

    # Configure the Training Op (for TRAIN mode)
    if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
        train_op = optimizer.minimize(
        loss=loss,
        global_step=tf.train.get_global_step())
        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

    # Add evaluation metrics (for EVAL mode)
    eval_metric_ops = {
      "accuracy": tf.metrics.accuracy(
          labels=labels, predictions=predictions["classes"])}
    return tf.estimator.EstimatorSpec(
      mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)

In [9]:
mnist_classifier = tf.estimator.Estimator(
    model_fn = cnn_model_fn,model_dir='./tmp/pingfen_convnet_model')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f69e465c290>, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_master': '', '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_model_dir': './tmp/pingfen_convnet_model', '_save_summary_steps': 100}


In [10]:
# Set up logging for predictions
tensors_to_log = {"probabilities": "softmax_tensor"}
logging_hook = tf.train.LoggingTensorHook(tensors=tensors_to_log, every_n_iter=50)

## 训练cnn模型

In [11]:
# Train the model
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": train_data},
    y=train_labels,
    batch_size=500,
    num_epochs=None,
    shuffle=True)
mnist_classifier.train(
    input_fn=train_input_fn,
    steps=20000,
    hooks=[logging_hook])

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from ./tmp/pingfen_convnet_model/model.ckpt-20000
INFO:tensorflow:Saving checkpoints for 20001 into ./tmp/pingfen_convnet_model/model.ckpt.
INFO:tensorflow:probabilities = [[0.00014775 0.00118833 0.00090027 0.04385887 0.24246219 0.7114426 ]
 [0.00000043 0.00023146 0.00167531 0.07054105 0.32724586 0.60030586]
 [0.00115522 0.02764106 0.05995301 0.14934221 0.26229778 0.49961066]
 ...
 [0.00043283 0.00752753 0.00438319 0.07313761 0.25316143 0.66135746]
 [0.00000171 0.00014193 0.00555609 0.13779409 0.37296593 0.48354018]
 [0.02396978 0.06482391 0.09996277 0.14773428 0.21547285 0.44803646]]
INFO:tensorflow:loss = 0.9304232, step = 20001
INFO:tensorflow:probabilities = [[0.00043903 0.00757462 0.03466894 0.15001269 0.2830425  0.52426225]
 [0.00005992 0.00233411 0.01474791 0.12201291 0.30385375 0.55699134]
 [0.00020909 0.00265054 0.00719917 0.08118352 0.2497919  0.65896577]
 ...
 [0.00000004 0.0000757  0.00156643 0

INFO:tensorflow:global_step/sec: 51.6978
INFO:tensorflow:probabilities = [[0.00000012 0.00000739 0.00034966 0.0381348  0.2700984  0.69140965]
 [0.01019657 0.05237481 0.02318002 0.11418241 0.23007163 0.56999457]
 [0.00000007 0.00120044 0.00468255 0.15211934 0.39101154 0.45098603]
 ...
 [0.         0.00000645 0.00012105 0.07821114 0.6596096  0.26205173]
 [0.00098777 0.0192467  0.03672789 0.14301829 0.26507005 0.53494936]
 [0.00463683 0.00448168 0.01841735 0.08145204 0.2402795  0.65073264]] (0.957 sec)
INFO:tensorflow:loss = 0.86632836, step = 20801 (1.932 sec)
INFO:tensorflow:probabilities = [[0.00007121 0.00254582 0.01627037 0.1220782  0.3051415  0.5538929 ]
 [0.00000655 0.00118602 0.00706519 0.12233355 0.33372003 0.5356887 ]
 [0.00032805 0.00182196 0.00150136 0.04664377 0.22127838 0.72842646]
 ...
 [0.00103545 0.00123745 0.01032256 0.05181941 0.20678665 0.72879845]
 [0.00060633 0.01116641 0.03491852 0.17320304 0.31311205 0.46699366]
 [0.00216701 0.01713034 0.06022504 0.16032913 0.28291

INFO:tensorflow:global_step/sec: 57.7726
INFO:tensorflow:probabilities = [[0.00095979 0.00620226 0.02434034 0.12193943 0.2845903  0.5619678 ]
 [0.00000365 0.00092751 0.00354304 0.08914425 0.3093807  0.59700084]
 [0.0000038  0.00010372 0.00163545 0.06322883 0.29357415 0.6414541 ]
 ...
 [0.00010183 0.00500651 0.01285667 0.12695237 0.3060739  0.5490088 ]
 [0.00012173 0.00193864 0.00497302 0.06084735 0.2234248  0.70869446]
 [0.00033215 0.01067691 0.01522131 0.10564856 0.28070334 0.5874178 ]] (0.903 sec)
INFO:tensorflow:loss = 0.9469331, step = 21601 (1.734 sec)
INFO:tensorflow:probabilities = [[0.00006775 0.00174062 0.00672235 0.07353158 0.25403437 0.6639033 ]
 [0.00000153 0.00020502 0.00094066 0.04279706 0.2502715  0.7057842 ]
 [0.00000119 0.00041936 0.0079275  0.13540517 0.35511664 0.5011301 ]
 ...
 [0.00000001 0.00000072 0.00004447 0.01962112 0.2622116  0.71812207]
 [0.00084324 0.00512588 0.0088617  0.07722574 0.24186496 0.6660784 ]
 [0.00000006 0.00006665 0.00035989 0.03824874 0.261967

INFO:tensorflow:global_step/sec: 54.3476
INFO:tensorflow:probabilities = [[0.00051732 0.0245516  0.0529344  0.16530754 0.2790258  0.47766334]
 [0.00000011 0.00203598 0.00517268 0.13929068 0.4095539  0.4439467 ]
 [0.00001013 0.00081564 0.00462948 0.09029673 0.30174288 0.602505  ]
 ...
 [0.02010148 0.01177278 0.01958976 0.06688067 0.19437754 0.6872778 ]
 [0.         0.00000657 0.00127901 0.11914167 0.44597137 0.4336014 ]
 [0.00003292 0.00109161 0.00694574 0.09255777 0.29421815 0.6051538 ]] (0.891 sec)
INFO:tensorflow:loss = 0.9145263, step = 22401 (1.843 sec)
INFO:tensorflow:probabilities = [[0.00198974 0.01853134 0.01723245 0.08577342 0.22208522 0.65438783]
 [0.00021188 0.0185139  0.03474177 0.19906855 0.32717952 0.42028433]
 [0.00002461 0.00141457 0.00137021 0.04165241 0.2065712  0.748967  ]
 ...
 [0.00000018 0.0000237  0.000815   0.04031817 0.25552526 0.7033177 ]
 [0.00179517 0.01375833 0.01831877 0.1079808  0.26505467 0.5930922 ]
 [0.00001593 0.00113971 0.00439538 0.10314701 0.309832

INFO:tensorflow:global_step/sec: 53.9517
INFO:tensorflow:probabilities = [[0.00000426 0.00029261 0.00139819 0.05340225 0.26842612 0.6764766 ]
 [0.00000309 0.00039337 0.00293359 0.0834509  0.31021857 0.6030005 ]
 [0.00022886 0.00439567 0.007988   0.09128001 0.2639157  0.6321918 ]
 ...
 [0.00059554 0.03689134 0.04313995 0.17476565 0.29600883 0.44859865]
 [0.00000666 0.0012602  0.00796565 0.10590596 0.3428654  0.5419962 ]
 [0.0002834  0.00637239 0.02475844 0.11296267 0.26277697 0.5928461 ]] (0.897 sec)
INFO:tensorflow:loss = 0.9933211, step = 23201 (1.872 sec)
INFO:tensorflow:probabilities = [[0.00000042 0.00013647 0.00142716 0.09706147 0.4009833  0.5003912 ]
 [0.00000075 0.00078288 0.00277531 0.06895889 0.29175884 0.6357233 ]
 [0.00021397 0.09229833 0.00945771 0.17925005 0.41938055 0.29939944]
 ...
 [0.00041131 0.00122692 0.00280246 0.04663563 0.21747464 0.731449  ]
 [0.00028824 0.00309943 0.01277531 0.10961048 0.28635135 0.5878751 ]
 [0.00021317 0.00531299 0.01626522 0.13962506 0.307480

INFO:tensorflow:global_step/sec: 53.9939
INFO:tensorflow:probabilities = [[0.0000877  0.00193073 0.00949592 0.11580027 0.3146581  0.5580273 ]
 [0.00271945 0.01550792 0.02819108 0.10247782 0.23642057 0.61468315]
 [0.00007234 0.00419861 0.01113826 0.10220652 0.2863392  0.596045  ]
 ...
 [0.00000368 0.0004322  0.00163742 0.06636994 0.2853376  0.64621925]
 [0.00001545 0.00031355 0.0028654  0.08201174 0.30284795 0.6119459 ]
 [0.00018742 0.01326527 0.02517567 0.13726532 0.2876305  0.53647584]] (0.932 sec)
INFO:tensorflow:loss = 0.92947334, step = 24001 (1.842 sec)
INFO:tensorflow:probabilities = [[0.00007313 0.002986   0.0018175  0.05264398 0.2318761  0.7106033 ]
 [0.00061478 0.02324036 0.00911259 0.10223569 0.27746984 0.58732677]
 [0.00346802 0.01019822 0.03310691 0.12458316 0.26528722 0.5633564 ]
 ...
 [0.00002515 0.00599598 0.0153817  0.14840166 0.5396675  0.29052797]
 [0.00003426 0.00224048 0.01323987 0.12685098 0.31975132 0.5378831 ]
 [0.00277183 0.01188666 0.02432071 0.09745283 0.24149

INFO:tensorflow:global_step/sec: 55.2388
INFO:tensorflow:probabilities = [[0.00010824 0.00245152 0.00549887 0.08130933 0.2671544  0.6434776 ]
 [0.00000001 0.00004262 0.001499   0.10933116 0.41774783 0.47137937]
 [0.00076811 0.026488   0.03403353 0.1547618  0.2982379  0.48571068]
 ...
 [0.00300709 0.01903196 0.0374053  0.12477218 0.25528267 0.5605008 ]
 [0.00004278 0.00430989 0.01219174 0.10949925 0.28616005 0.5877963 ]
 [0.00000366 0.0001542  0.00353371 0.05868017 0.26913053 0.6684976 ]] (0.897 sec)
INFO:tensorflow:loss = 0.9142726, step = 24801 (1.815 sec)
INFO:tensorflow:probabilities = [[0.00310422 0.0110055  0.01349493 0.07968281 0.22418721 0.66852534]
 [0.00000761 0.00891112 0.00582059 0.12180597 0.354632   0.50882274]
 [0.00082089 0.00893566 0.01068744 0.11310478 0.27631527 0.59013593]
 ...
 [0.00000007 0.00085901 0.00366944 0.15312016 0.5012261  0.3411251 ]
 [0.00079255 0.00238304 0.0046629  0.04446698 0.18899833 0.7586962 ]
 [0.0000344  0.0015008  0.00727965 0.09725492 0.291246

INFO:tensorflow:global_step/sec: 52.9288
INFO:tensorflow:probabilities = [[0.00007108 0.00233966 0.02355548 0.16655895 0.32437006 0.48310488]
 [0.00000109 0.00018892 0.00118754 0.06017455 0.29650465 0.6419433 ]
 [0.00003913 0.0007418  0.00180766 0.04670176 0.22881547 0.7218942 ]
 ...
 [0.00000207 0.0007867  0.00683283 0.11863624 0.35996965 0.5137726 ]
 [0.00025821 0.00484524 0.00859796 0.09252994 0.2824113  0.6113574 ]
 [0.00000385 0.01090632 0.01922468 0.16701542 0.34326154 0.4595882 ]] (0.964 sec)
INFO:tensorflow:loss = 0.9490504, step = 25601 (1.886 sec)
INFO:tensorflow:probabilities = [[0.00131081 0.00174098 0.00891293 0.05100979 0.20678435 0.73024124]
 [0.00291022 0.00478173 0.02302941 0.10721555 0.2637548  0.59830827]
 [0.00001734 0.00156505 0.00162363 0.06020222 0.26582578 0.67076606]
 ...
 [0.00146257 0.01295618 0.02714412 0.13440889 0.2805078  0.54352045]
 [0.00000062 0.0001439  0.00058884 0.04153243 0.2490442  0.70869   ]
 [0.0000001  0.00000638 0.00044599 0.02758657 0.288187

INFO:tensorflow:global_step/sec: 56.1836
INFO:tensorflow:probabilities = [[0.00004419 0.00107438 0.00271109 0.06577838 0.26325333 0.66713864]
 [0.0000257  0.01668273 0.01242287 0.11595034 0.329248   0.5256704 ]
 [0.00000018 0.00020802 0.00242857 0.11081567 0.40108532 0.4854623 ]
 ...
 [0.00818042 0.00734255 0.00495794 0.06576512 0.22029956 0.6934545 ]
 [0.00917513 0.03802723 0.04655384 0.14847799 0.2700531  0.48771265]
 [0.00013298 0.00211107 0.00536645 0.06333213 0.24155173 0.68750566]] (0.869 sec)
INFO:tensorflow:loss = 0.94766283, step = 26401 (1.777 sec)
INFO:tensorflow:probabilities = [[0.00006463 0.01056651 0.01531023 0.12993246 0.30488938 0.53923684]
 [0.00000007 0.00007056 0.00162466 0.07070312 0.34088445 0.5867171 ]
 [0.00022717 0.00391431 0.03142307 0.13649552 0.29510254 0.5328374 ]
 ...
 [0.00129593 0.021004   0.01406583 0.10224648 0.25887746 0.60251033]
 [0.00896583 0.03679644 0.04682482 0.13205536 0.25088528 0.5244723 ]
 [0.07464851 0.0777837  0.07761295 0.12336116 0.19636

INFO:tensorflow:global_step/sec: 54.4669
INFO:tensorflow:probabilities = [[0.00004262 0.00439    0.02069391 0.15672147 0.32822818 0.4899239 ]
 [0.00000214 0.00044604 0.0036832  0.12726691 0.36564404 0.50295764]
 [0.00041783 0.02622391 0.01768663 0.15040576 0.32525367 0.4800122 ]
 ...
 [0.00000685 0.00010662 0.00034556 0.02479971 0.20020722 0.77453405]
 [0.00012098 0.00288689 0.00450486 0.06912018 0.2501877  0.6731794 ]
 [0.00011073 0.00261779 0.00918098 0.10335667 0.2917097  0.59302413]] (0.896 sec)
INFO:tensorflow:loss = 0.97870433, step = 27201 (1.833 sec)
INFO:tensorflow:probabilities = [[0.00000003 0.00023005 0.00198997 0.14081101 0.50802016 0.34894878]
 [0.00000118 0.0001552  0.00211829 0.08897525 0.33467558 0.5740745 ]
 [0.00000105 0.00003527 0.00003999 0.01101919 0.13939932 0.8495052 ]
 ...
 [0.         0.00003162 0.00036454 0.04931775 0.3267623  0.6235238 ]
 [0.00002201 0.00517785 0.00296118 0.05876778 0.23881987 0.6942513 ]
 [0.0041189  0.21996097 0.04447094 0.14560938 0.25997

INFO:tensorflow:global_step/sec: 57.5739
INFO:tensorflow:probabilities = [[0.00001729 0.00154983 0.00186991 0.06253002 0.26749346 0.66653955]
 [0.00000001 0.00001888 0.0001386  0.02494617 0.24563853 0.7292578 ]
 [0.00065653 0.00308053 0.00825113 0.09805453 0.27759093 0.6123664 ]
 ...
 [0.00070055 0.01192236 0.02545509 0.1395388  0.28634933 0.53603387]
 [0.00422846 0.01442357 0.00726555 0.06069842 0.22420272 0.68918127]
 [0.00001575 0.0052711  0.01500769 0.15914223 0.3462463  0.47431687]] (0.910 sec)
INFO:tensorflow:loss = 0.9529913, step = 28001 (1.743 sec)
INFO:tensorflow:probabilities = [[0.00000231 0.00099611 0.00015349 0.02297962 0.23200516 0.74386334]
 [0.00002753 0.0045164  0.0111463  0.10096634 0.28628042 0.59706295]
 [0.00003127 0.00051349 0.00341337 0.04506304 0.19901869 0.75196016]
 ...
 [0.00000016 0.00019819 0.00280843 0.10486328 0.3821013  0.51002866]
 [0.00000185 0.00027369 0.00145918 0.06644823 0.30636796 0.6254491 ]
 [0.00003361 0.00483054 0.00694816 0.0828273  0.265057

INFO:tensorflow:global_step/sec: 51.2636
INFO:tensorflow:probabilities = [[0.00004903 0.00035086 0.00039574 0.02320241 0.17790677 0.7980952 ]
 [0.00850619 0.02254024 0.0396671  0.10924132 0.23863201 0.58141315]
 [0.00001519 0.0004769  0.00204041 0.05980248 0.26741993 0.6702451 ]
 ...
 [0.00217106 0.03821551 0.02763661 0.12431256 0.27182457 0.5358397 ]
 [0.00465789 0.00956884 0.00933829 0.06391024 0.20925571 0.703269  ]
 [0.00423652 0.03582416 0.02414159 0.15233654 0.31487066 0.46859056]] (0.996 sec)
INFO:tensorflow:loss = 0.96528506, step = 28801 (1.953 sec)
INFO:tensorflow:probabilities = [[0.00025241 0.00349135 0.00774555 0.08844582 0.2686624  0.63140243]
 [0.00180629 0.00377641 0.01587573 0.08895744 0.25475332 0.63483083]
 [0.00053306 0.00867911 0.00756888 0.08682601 0.28021905 0.61617386]
 ...
 [0.01398452 0.05131467 0.0258642  0.10254522 0.22383462 0.58245677]
 [0.00000322 0.00016871 0.00234971 0.07321481 0.30176476 0.62249875]
 [0.00000356 0.00643318 0.01345206 0.18360093 0.39807

INFO:tensorflow:global_step/sec: 53.386
INFO:tensorflow:probabilities = [[0.00019995 0.00429562 0.02962082 0.14900014 0.3121904  0.50469315]
 [0.00134923 0.01857801 0.03212637 0.12598191 0.26285812 0.5591064 ]
 [0.00000024 0.00048178 0.00382839 0.14057232 0.38996977 0.46514747]
 ...
 [0.00000004 0.00000308 0.00033039 0.04779433 0.36525217 0.58662   ]
 [0.00051784 0.0142066  0.0106976  0.10237008 0.27463707 0.5975708 ]
 [0.00936364 0.01192976 0.01995402 0.07382111 0.21011665 0.6748148 ]] (0.977 sec)
INFO:tensorflow:loss = 0.94189185, step = 29601 (1.874 sec)
INFO:tensorflow:probabilities = [[0.00000842 0.00045045 0.00279685 0.04607872 0.22773632 0.7229292 ]
 [0.00896411 0.03207592 0.01892434 0.09118852 0.22391161 0.6249355 ]
 [0.         0.00000859 0.00019945 0.03920681 0.3367741  0.623811  ]
 ...
 [0.00000495 0.00089199 0.00057781 0.03317958 0.20507914 0.76026654]
 [0.00005129 0.01409999 0.03082203 0.14699572 0.30132574 0.5067052 ]
 [0.00067577 0.00418768 0.01084066 0.09119406 0.263645

INFO:tensorflow:global_step/sec: 54.1511
INFO:tensorflow:probabilities = [[0.00006103 0.00781397 0.01268861 0.11931191 0.3088437  0.55128086]
 [0.00031164 0.00121584 0.00185312 0.03664486 0.19190134 0.76807326]
 [0.00000004 0.00008684 0.00121679 0.05915531 0.33172804 0.607813  ]
 ...
 [0.         0.00008747 0.00032543 0.02681818 0.27417505 0.69859385]
 [0.01671782 0.02871699 0.0198237  0.08757703 0.21838449 0.62878   ]
 [0.0000648  0.00180768 0.00482457 0.0872207  0.2890493  0.61703295]] (0.871 sec)
INFO:tensorflow:loss = 0.9564103, step = 30401 (1.845 sec)
INFO:tensorflow:probabilities = [[0.0000004  0.00125383 0.0082073  0.12782933 0.3598385  0.5028707 ]
 [0.00006447 0.00676814 0.01195137 0.08647517 0.2598388  0.634902  ]
 [0.00000055 0.00143312 0.00569757 0.09776103 0.34409928 0.55100846]
 ...
 [0.00124266 0.00990111 0.02605721 0.09516655 0.23652412 0.63110834]
 [0.00000691 0.00135013 0.00310451 0.07318451 0.2890267  0.63332725]
 [0.00000055 0.00151339 0.00494691 0.15483618 0.405093

INFO:tensorflow:global_step/sec: 51.7291
INFO:tensorflow:probabilities = [[0.00341396 0.03245392 0.01971987 0.05120648 0.17330968 0.719896  ]
 [0.00000483 0.00004619 0.00011108 0.00677951 0.09935337 0.89370507]
 [0.00014269 0.00405781 0.01650464 0.09859352 0.27703038 0.6036709 ]
 ...
 [0.00046121 0.01392934 0.02670949 0.09970845 0.24292444 0.616267  ]
 [0.00000016 0.00012842 0.00175816 0.0528342  0.27416104 0.671118  ]
 [0.00016146 0.00414809 0.01220122 0.07351215 0.2395509  0.67042613]] (0.998 sec)
INFO:tensorflow:loss = 0.9396669, step = 31201 (1.930 sec)
INFO:tensorflow:probabilities = [[0.00006663 0.00330244 0.0087919  0.11360762 0.2961106  0.5781209 ]
 [0.00001136 0.00404938 0.02001948 0.18715748 0.35369688 0.4350654 ]
 [0.00000357 0.00146189 0.00481926 0.11278204 0.3380489  0.54288435]
 ...
 [0.         0.00007662 0.00059431 0.06804059 0.35628954 0.57499886]
 [0.00000009 0.00036292 0.00572251 0.12466318 0.39204162 0.47720972]
 [0.00034033 0.02759579 0.04642234 0.15687834 0.283994

INFO:tensorflow:global_step/sec: 55.8803
INFO:tensorflow:probabilities = [[0.00000062 0.00047849 0.00379895 0.08984423 0.3340323  0.5718454 ]
 [0.00859095 0.0203367  0.03073976 0.10250701 0.23509967 0.6027259 ]
 [0.00004972 0.00378205 0.00887657 0.0965382  0.28701517 0.60373825]
 ...
 [0.0017771  0.01428351 0.01122781 0.0708854  0.21815161 0.6836746 ]
 [0.00000208 0.00191843 0.00628526 0.11609744 0.32821563 0.5474811 ]
 [0.00003623 0.00313427 0.01252964 0.08246188 0.2615109  0.6403271 ]] (0.821 sec)
INFO:tensorflow:loss = 0.9445115, step = 32001 (1.787 sec)
INFO:tensorflow:probabilities = [[0.00002647 0.00075078 0.01469019 0.11760031 0.33283973 0.5340925 ]
 [0.00000156 0.00140013 0.00111985 0.04520519 0.2369785  0.7152948 ]
 [0.00005907 0.00109715 0.00582799 0.05358587 0.22516765 0.7142623 ]
 ...
 [0.00021016 0.01278053 0.02687511 0.1495047  0.3200387  0.49059078]
 [0.00012816 0.01744949 0.01616866 0.12383919 0.29007578 0.55233866]
 [0.00000005 0.00011148 0.0000792  0.02458516 0.225572

INFO:tensorflow:global_step/sec: 52.0053
INFO:tensorflow:probabilities = [[0.00005809 0.00585048 0.02731305 0.14978258 0.31533292 0.5016628 ]
 [0.00000027 0.00017803 0.00159693 0.06524078 0.2997747  0.6332093 ]
 [0.00067806 0.00980601 0.0224323  0.12335286 0.28656548 0.5571653 ]
 ...
 [0.00007366 0.00598587 0.00288488 0.04892333 0.22036232 0.7217699 ]
 [0.00018875 0.00145689 0.00603307 0.0544701  0.22098266 0.7168686 ]
 [0.00000076 0.00069594 0.00545682 0.10046139 0.33475527 0.5586298 ]] (0.962 sec)
INFO:tensorflow:loss = 0.90770537, step = 32801 (1.922 sec)
INFO:tensorflow:probabilities = [[0.00000008 0.00000074 0.0004467  0.04201743 0.26462153 0.6929135 ]
 [0.00000412 0.0041052  0.00920227 0.11776597 0.34660366 0.5223188 ]
 [0.0064262  0.04673653 0.03994097 0.15413013 0.28330377 0.46946236]
 ...
 [0.00020688 0.00130043 0.00183544 0.03603691 0.19383736 0.766783  ]
 [0.         0.00017451 0.00271653 0.14976661 0.4393489  0.40799344]
 [0.0027535  0.02267848 0.05100808 0.13968916 0.25900

INFO:tensorflow:global_step/sec: 55.401
INFO:tensorflow:probabilities = [[0.0001614  0.00134346 0.011508   0.11515371 0.3063445  0.5654889 ]
 [0.00009335 0.00157173 0.00344735 0.06904615 0.2547374  0.671104  ]
 [0.01299111 0.01506081 0.02264666 0.0844058  0.2231513  0.6417444 ]
 ...
 [0.00001718 0.00189199 0.00360685 0.06400339 0.24820901 0.6822716 ]
 [0.00032387 0.00288263 0.00841346 0.05084749 0.20304148 0.73449105]
 [0.00000163 0.00131019 0.00842141 0.15141942 0.413387   0.42546037]] (0.952 sec)
INFO:tensorflow:loss = 0.9720855, step = 33601 (1.805 sec)
INFO:tensorflow:probabilities = [[0.00001364 0.00013386 0.00044484 0.01995876 0.17076722 0.80868167]
 [0.00034481 0.01122055 0.0103382  0.09930822 0.27133858 0.6074497 ]
 [0.00004128 0.0044673  0.01294921 0.12343294 0.3133766  0.5457326 ]
 ...
 [0.00000864 0.00111266 0.00602797 0.11526588 0.3166739  0.56091094]
 [0.0016345  0.02444371 0.04104437 0.12888303 0.25800988 0.54598457]
 [0.00234462 0.02384905 0.02737557 0.10351948 0.2431519

INFO:tensorflow:global_step/sec: 54.4623
INFO:tensorflow:probabilities = [[0.00004701 0.00817402 0.0143275  0.15758027 0.39191407 0.42795715]
 [0.00010817 0.00163573 0.00207398 0.04519203 0.22059056 0.7303995 ]
 [0.00002993 0.00167262 0.00511443 0.06084253 0.24212539 0.6902151 ]
 ...
 [0.00000093 0.00155001 0.00857291 0.17651811 0.4256026  0.38775542]
 [0.00022148 0.0281304  0.04133531 0.16342673 0.2995868  0.46729922]
 [0.01070143 0.03988984 0.06034499 0.12551834 0.2402186  0.52332675]] (0.866 sec)
INFO:tensorflow:loss = 0.871413, step = 34401 (1.839 sec)
INFO:tensorflow:probabilities = [[0.00015522 0.01032887 0.02955164 0.15165377 0.3211489  0.48716167]
 [0.00007525 0.00076923 0.00106173 0.04483392 0.22772798 0.7255319 ]
 [0.00022864 0.00294522 0.00732463 0.07227687 0.24348679 0.6737379 ]
 ...
 [0.00000158 0.00009648 0.00122066 0.03524973 0.22106779 0.74236375]
 [0.01436554 0.07223548 0.06834613 0.15333475 0.27268696 0.4190312 ]
 [0.00395739 0.01433595 0.02783132 0.12114178 0.2601453

INFO:tensorflow:global_step/sec: 53.8025
INFO:tensorflow:probabilities = [[0.00120606 0.00953433 0.00658638 0.06266631 0.22039472 0.69961214]
 [0.00000159 0.00019374 0.00126536 0.03746121 0.22795147 0.73312664]
 [0.00000251 0.00299544 0.00827172 0.12690479 0.33781782 0.52400774]
 ...
 [0.01206843 0.03280195 0.02398622 0.09491513 0.2265849  0.60964334]
 [0.00631113 0.00511541 0.01387567 0.0866677  0.24913532 0.63889474]
 [0.00243438 0.00709162 0.0054561  0.05198855 0.19655406 0.7364753 ]] (0.905 sec)
INFO:tensorflow:loss = 0.96986693, step = 35201 (1.852 sec)
INFO:tensorflow:probabilities = [[0.00000803 0.00212123 0.01045927 0.092972   0.2804894  0.61395   ]
 [0.00000003 0.00036009 0.00532857 0.16872543 0.41180384 0.41378203]
 [0.0000033  0.00189352 0.00598199 0.08825259 0.30093974 0.6029288 ]
 ...
 [0.         0.00014679 0.00250025 0.12532921 0.498826   0.3731978 ]
 [0.00006494 0.00669745 0.00666363 0.11243748 0.32776976 0.5463668 ]
 [0.00010038 0.01192706 0.0274541  0.12038065 0.27625

INFO:tensorflow:global_step/sec: 54.466
INFO:tensorflow:probabilities = [[0.00000176 0.00152109 0.00489728 0.09774993 0.3202255  0.5756045 ]
 [0.00037908 0.01066121 0.0329378  0.14043418 0.28544414 0.53014356]
 [0.00000014 0.00016526 0.00167823 0.05083622 0.32718995 0.6201302 ]
 ...
 [0.00022176 0.14588237 0.01740077 0.261494   0.39284205 0.18215913]
 [0.00000593 0.00052455 0.00401932 0.06798891 0.28063172 0.64682955]
 [0.00057835 0.00922356 0.00065981 0.03319477 0.18408777 0.77225584]] (0.965 sec)
INFO:tensorflow:loss = 0.92148525, step = 36001 (1.837 sec)
INFO:tensorflow:probabilities = [[0.02195548 0.05832125 0.08445838 0.14777161 0.23172504 0.45576826]
 [0.00000026 0.0004615  0.00153948 0.06226012 0.31824806 0.6174906 ]
 [0.00000324 0.00139031 0.00308226 0.08323999 0.301902   0.6103822 ]
 ...
 [0.00006694 0.00833282 0.01363264 0.11572924 0.2983844  0.5638539 ]
 [0.00000874 0.00129725 0.00379859 0.07457235 0.2805577  0.63976544]
 [0.00004314 0.01078202 0.0089235  0.15604764 0.389378

INFO:tensorflow:global_step/sec: 53.5392
INFO:tensorflow:probabilities = [[0.00005562 0.00251724 0.00518961 0.10088973 0.30271783 0.58862996]
 [0.00000136 0.00002865 0.00094542 0.06295828 0.32424918 0.61181706]
 [0.00068747 0.00039715 0.00094376 0.03166134 0.19377522 0.77253497]
 ...
 [0.0004594  0.01365294 0.02899437 0.1444008  0.31445438 0.49803802]
 [0.00002318 0.00183176 0.01114422 0.12507781 0.32753256 0.5343904 ]
 [0.00029036 0.0040903  0.01360846 0.08302186 0.25840384 0.6405851 ]] (0.914 sec)
INFO:tensorflow:loss = 0.9226439, step = 36801 (1.862 sec)
INFO:tensorflow:probabilities = [[0.00002372 0.00462843 0.00734774 0.11448493 0.3061327  0.5673826 ]
 [0.00000023 0.00071694 0.00498339 0.05945797 0.2524315  0.68241   ]
 [0.00066568 0.04245838 0.05610062 0.1509054  0.26753393 0.48233598]
 ...
 [0.00000141 0.00031356 0.00333876 0.06200903 0.395046   0.53929126]
 [0.00149314 0.00575034 0.00696183 0.06122191 0.22418605 0.7003867 ]
 [0.01003552 0.02790994 0.06635853 0.13321406 0.245492

INFO:tensorflow:global_step/sec: 52.7986
INFO:tensorflow:probabilities = [[0.00000398 0.00271239 0.00931173 0.0961475  0.31756073 0.5742637 ]
 [0.00048153 0.00805305 0.01320755 0.1516081  0.34422097 0.48242885]
 [0.00000019 0.00067661 0.00775436 0.15633518 0.394401   0.44083264]
 ...
 [0.         0.00000162 0.0000066  0.01002959 0.2116581  0.7783041 ]
 [0.0000003  0.00036656 0.00103715 0.04790315 0.27607325 0.67461956]
 [0.00002484 0.00297447 0.00509951 0.08988971 0.2882784  0.61373305]] (0.950 sec)
INFO:tensorflow:loss = 0.86219287, step = 37601 (1.894 sec)
INFO:tensorflow:probabilities = [[0.0007326  0.01281013 0.03027229 0.15513082 0.32794335 0.47311077]
 [0.00117219 0.01009188 0.01019596 0.07815148 0.24069239 0.6596961 ]
 [0.00003815 0.00545246 0.01107895 0.10884946 0.30027017 0.5743108 ]
 ...
 [0.00205673 0.0147267  0.01368023 0.07621276 0.22469632 0.66862726]
 [0.00001855 0.01849143 0.02746692 0.16727267 0.3369298  0.44982064]
 [0.00005147 0.0001272  0.00010497 0.01264591 0.13141

INFO:tensorflow:global_step/sec: 51.965
INFO:tensorflow:probabilities = [[0.00000916 0.00427125 0.0144118  0.11738185 0.31393665 0.5499893 ]
 [0.00043939 0.03458076 0.02664563 0.20612414 0.39567673 0.33653334]
 [0.00009052 0.00454379 0.00340609 0.05112796 0.22777972 0.7130519 ]
 ...
 [0.00000546 0.00083191 0.00316823 0.06196992 0.27399617 0.6600283 ]
 [0.00000096 0.00073582 0.00492175 0.10801136 0.34918323 0.53714687]
 [0.00032214 0.00686506 0.03388092 0.19416244 0.28307775 0.48169166]] (1.013 sec)
INFO:tensorflow:loss = 0.93213695, step = 38401 (1.921 sec)
INFO:tensorflow:probabilities = [[0.00001149 0.001887   0.01412755 0.13320614 0.33546466 0.5153032 ]
 [0.00008194 0.00275507 0.0144092  0.10368449 0.28900725 0.590062  ]
 [0.00000775 0.0000956  0.00039565 0.01676924 0.14725733 0.83547443]
 ...
 [0.00000343 0.00078184 0.00367571 0.06305715 0.27954128 0.65294063]
 [0.00037341 0.00159126 0.00168931 0.03136776 0.17590532 0.78907293]
 [0.00017218 0.00600522 0.01505214 0.09921667 0.278635

INFO:tensorflow:global_step/sec: 54.7236
INFO:tensorflow:probabilities = [[0.00002204 0.00132623 0.00658248 0.06889575 0.26746714 0.65570635]
 [0.00245804 0.00770717 0.00712439 0.0586017  0.20978045 0.7143282 ]
 [0.00002415 0.00538673 0.02052478 0.15100124 0.35353383 0.46952927]
 ...
 [0.00002035 0.00785381 0.0061472  0.07795008 0.26272306 0.6453055 ]
 [0.00000001 0.00003874 0.00003565 0.02171635 0.23609501 0.74211425]
 [0.0001421  0.01178906 0.01497282 0.10314125 0.2764431  0.5935117 ]] (0.929 sec)
INFO:tensorflow:loss = 0.9055774, step = 39201 (1.818 sec)
INFO:tensorflow:probabilities = [[0.00001304 0.00098987 0.00248067 0.03946521 0.20120116 0.75585   ]
 [0.00000023 0.00023135 0.00209685 0.07623906 0.32535157 0.59608096]
 [0.00000317 0.00070253 0.00201117 0.06134425 0.271773   0.66416585]
 ...
 [0.00000021 0.00006492 0.00010712 0.01707681 0.18348475 0.7992661 ]
 [0.00000174 0.00415134 0.01188025 0.16461356 0.40487576 0.41447732]
 [0.00000212 0.00004341 0.00002714 0.00609598 0.104766

INFO:tensorflow:Saving checkpoints for 40000 into ./tmp/pingfen_convnet_model/model.ckpt.
INFO:tensorflow:Loss for final step: 0.9487269.


## 评估模型

In [12]:
eval_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": eval_data},
    y=eval_labels,
    num_epochs=1,
    shuffle=False)
eval_results = mnist_classifier.evaluate(input_fn=eval_input_fn)
print(eval_results)

INFO:tensorflow:Starting evaluation at 2018-03-12-04:02:28
INFO:tensorflow:Restoring parameters from ./tmp/pingfen_convnet_model/model.ckpt-40000
INFO:tensorflow:Finished evaluation at 2018-03-12-04:02:29
INFO:tensorflow:Saving dict for global step 40000: accuracy = 0.6092, global_step = 40000, loss = 0.9042214
{'loss': 0.9042214, 'global_step': 40000, 'accuracy': 0.6092}


In [13]:
pd_predict = pd.read_csv('./data/pd_predict.csv',index=False)